POST https://edtechmanagement.herokuapp.com/user/signup
Content-Type: application/json

{
	"first_name":"Priya",
	"last_name":"Sahastrabudhhe",
	"email":"Priya@mailinator.com",
	"mobile":"+912334567980",
	"password":"iamthehottest"   
}

###
POST https://edtechmanagement.herokuapp.com/user/signup
Content-Type: application/json

{
	"first_name":"Atul",
	"last_name":"Tiwari",
	"email":"atul@mailinator.com",
	"mobile":"+919876543100",
	"password":"iamthebest",
	"roleId":"6308af1349edd535fef6f33e"   
}

###
POST https://edtechmanagement.herokuapp.com/user/signup
Content-Type: application/json

{
	"first_name":"Viru",
	"last_name":"Sahastrabudhhe",
	"email":"virus@mailinator.com",
	"mobile":"+919876543210",
	"password":"iamthebest",
	"roleId":"6308b00249edd535fef6f341"   
}

###
POST https://edtechmanagement.herokuapp.com/user/signin
Content-Type: application/json

{
    "email": "virus@mailinator.com",
    "password": "iamthebest"
}
###
POST https://edtechmanagement.herokuapp.com/user/signin
Content-Type: application/json

{
    "email": "priya@mailinator.com",
    "password": "iamthehottest"
}

###
GET https://edtechmanagement.herokuapp.com/user

###
GET https://edtechmanagement.herokuapp.com/user/6308b31438c5dceb87808de9

###
POST https://edtechmanagement.herokuapp.com/role
Content-Type: application/json

{
    "name": "Admin",
    "scopes": [
        "user-get",
		"user-create",
		"student-get",
		"student-create",
		"role-get",
		"school-get",
		"school-create",
		"school-students"
    ]
}

###
GET https://edtechmanagement.herokuapp.com/role

###
POST https://edtechmanagement.herokuapp.com/school
Content-Type: application/json

{
    "name": "All India Institute Of Medical Science",
    "city": "New Delhi",
    "state": "Delhi",
    "country": "India"
}

###
GET https://edtechmanagement.herokuapp.com/school

###
POST https://edtechmanagement.herokuapp.com/student
Content-Type: application/json

{
    "name":"Priya Sahastrabudhhe",
    "userId":"6308e24b997f35e25c7ff97b",
    "schoolId":"6308e1f4997f35e25c7ff978"
}

###
GET https://edtechmanagement.herokuapp.com/student

###
GET https://edtechmanagement.herokuapp.com/school/students